### ISSUE TITLE
Error running workflow

### ISSUE THREAD

**Issue by finnbenned** [smith-chem-wisc/Spritz#181]
Hi,

Our team is using MSMS to study heart diseases and are getting access to RNA-Seq data. Your software looks to potentially be very useful.I have installed Docker Desktop and been trying to run your suggested 'Test it out' but so far w/ success as the program terminates with errors, lately after completing 9 of 26 steps (35%) 

I have mounted my drives and My Docker Desktop resource settings are as follows:

![docker setting](https://user-images.githubusercontent.com/69514407/89898325-ce636880-dbe0-11ea-95ab-2ca51a6c4b21.png)

The log file contains:

[workflow_2020-08-11-12-19-19.txt](https://github.com/smith-chem-wisc/Spritz/files/5056974/workflow_2020-08-11-12-19-19.txt)

Would be great if you could help out-.

Best,

Finn

**Comment by trishorts** [comment]
thanks for reporting the error. There is a couple things you can try. You can rename to the log file and start the run again. It will go faster, having already completed the initial steps. Some times the workflow has to be restarted a couple times to complete.

One thing that was worked better for me is to update my docker to allow WSL 2 (windows subsystem for linux). It can be a little hard to do the update. But, I think that it will be worth it. Let us know how it goes. We can provide additional support.

https://docs.microsoft.com/en-us/windows/wsl/wsl2-index

![image](https://user-images.githubusercontent.com/16841846/89898796-eddd9f80-dba6-11ea-9e3b-92ecd8bea908.png)

**Comment by finnbenned** [comment]
Thnx for your answer. Sorry to be a bit slow here but what is meant/what steps are done to “You can rename to the log file”?

Best,

Finn

Finn Benned Hansen
Ph.D
Visiting Scientist

Dept. of Biomedical Sciences
Faculty of Health and Medical Sciences
The Lundby Lab (https://www.cardiacproteomics.com)
University of Copenhagen
Blegdamsvej 3B
Deliveries to Nørre Allé 14 | Mærsk Tower | Room 07-09-11
2200 Copenhagen N
Denmark
Phone +45 42349464

**Comment by trishorts** [comment]
I apologize. I type too fast and leave many errors in my wake.

I meant that you can rename to existing log file to something else to preserve the contents. Then restart. A new log file will be generated. 

If you just restart, the new log file will overwrite the original and you won't be able to see what was there in the previous attempt. This can help with debugging. 

Does that help?

**Comment by finnbenned** [comment]
Yes, thnx, got it. Will try to upgrade to WSL2 – but we’re strictly managed by our university IT dept.

Currently trying to run two fastq files but also here get the following error several times (job keeps on running though) :

[Tue Aug 11 13:19:14 2020]
rule download_snpeff:
    output: SnpEff/snpEff.config, SnpEff/snpEff.jar
    log: data/SnpEffInstall.log
    jobid: 5

[Tue Aug 11 13:20:56 2020]
Error in rule download_snpeff:
    jobid: 5
    output: SnpEff/snpEff.config, SnpEff/snpEff.jar
    log: data/SnpEffInstall.log

RuleException:
CalledProcessError in line 11 of /app/rules/variants.smk:
Command ' set -euo pipefail;
        (rm -rf SnpEff
        git clone --depth=1 https://github.com/smith-chem-wisc/SnpEff
        cd SnpEff
        mvn install:install-file -Dfile=lib/antlr-4.5.1-complete.jar -DgroupId=org.antlr -DartifactId=antlr -Dversion=4.5.1 -Dpackaging=jar
        mvn install:install-file -Dfile=lib/biojava3-core-3.0.7.jar -DgroupId=org.biojava -DartifactId=biojava3-core -Dversion=3.0.7 -Dpackaging=jar
        mvn install:install-file -Dfile=lib/biojava3-structure-3.0.7.jar -DgroupId=org.biojava -DartifactId=biojava3-structure -Dversion=3.0.7 -Dpackaging=jar
        export VERSION=4.3
        export VERSION_UND=`echo $VERSION | tr '.' '_'`
        mvn clean compile assembly:assembly
        mvn install:install-file -Dfile=target/SnpEff-$VERSION.jar -DgroupId=org.snpeff -DartifactId=SnpEff -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true --quiet
        cp target/SnpEff-$VERSION-jar-with-dependencies.jar snpEff.jar
        cd ..) &> data/SnpEffInstall.log ' returned non-zero exit status 1.
  File "/app/rules/variants.smk", line 11, in __rule_download_snpeff
  File "/usr/local/envs/spritz/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job download_snpeff since they might be corrupted:
SnpEff/snpEff.config

Any ideas?

Best,

Finn

**Comment by acesnik** [comment]
Hi there, 

I believe this error is fixed in the upcoming release. Please stay tuned, and I'll try to have that out today or tomorrow.

If you could provide the `data/SnpEffInstall.log` file and the output of `docker info` from the CMD or Powershell terminals, that might be helpful.

My best guess for why this is happening is that the `maven` libraries needed to build SnpEff aren't installing properly, so the upcoming release avoids that entirely.

Best regards,

Anthony

**Comment by finnbenned** [comment]
Hi Anthony,

Great, looking forward to the new release.

Attach the SnpEffInstall log file. Below is the output from docker info w/o any containers running – hope ok:

PS C:\Users\pgl367> docker info
Client:
Debug Mode: false

Server:
Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
Images: 2
Server Version: 19.03.12
Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
init version: fec3683
Security Options:
  seccomp
   Profile: default
Kernel Version: 4.19.76-linuxkit
Operating System: Docker Desktop
OSType: linux
Architecture: x86_64
CPUs: 7
Total Memory: 49.53GiB
Name: docker-desktop
ID: KDSO:HOIQ:OAC6:2V6E:U567:4PC7:CJWR:PQTZ:5RI5:OTT5:EVKM:ZR6M
Docker Root Dir: /var/lib/docker
Debug Mode: true
  File Descriptors: 39
  Goroutines: 51
  System Time: 2020-08-12T11:19:54.628520958Z
  EventsListeners: 4
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
  127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

My Windows version (Ver 1909, Build 18363.959) is btw too old to install WSL 2 – and Windows upgrades are tightly managed by our IP dept, so regrettably ptobably not an avenue to pursue.

Thanks again for your support,

Finn

**Comment by acesnik** [comment]
Hi Finn,

The `docker info` output all looks okay, and it should work without WSL2 given those settings.

I've committed the simplified installation of our customized SnpEff fork here https://github.com/smith-chem-wisc/Spritz/pull/183. You should be able to use the current version (0.1.3) again, and it will automatically download the updated docker image with these changes.

Best regards,

Anthony

**Comment by finnbenned** [comment]
Hi Anthony,

Unfortunately I still get errors icw downloading SnpEff_4.3_SmithChemWisc_v2.zip (Docker log):

log: data/TransferUniProtModifications.build.log
jobid: 6
[Thu Aug 13 10:47:53 2020]
rule download_snpeff:
output: SnpEff/snpEff.config, SnpEff/snpEff.jar, SnpEff_4.3_SmithChemWisc_v2.zip
log: data/SnpEffInstall.log
jobid: 8
[Thu Aug 13 10:47:53 2020]
rule tmpdir:
output: tmp, temporary
jobid: 3
[Thu Aug 13 10:47:53 2020]
Finished job 3.
1 of 17 steps (6%) done
[Thu Aug 13 10:48:04 2020]
Finished job 6.
2 of 17 steps (12%) done
[Thu Aug 13 10:49:45 2020]
Error in rule download_snpeff:
jobid: 8
output: SnpEff/snpEff.config, SnpEff/snpEff.jar, SnpEff_4.3_SmithChemWisc_v2.zip
log: data/SnpEffInstall.log
RuleException:
CalledProcessError in line 12 of /app/rules/variants.smk:
Command ' set -euo pipefail; (wget https://github.com/smith-chem-wisc/SnpEff/releases/download/4.3_SCW1/SnpEff_4.3_SmithChemWisc_v2.zip && unzip SnpEff_4.3_SmithChemWisc_v2.zip -d SnpEff) &> data/SnpEffInstall.log ' returned non-zero exit status 127.
File "/app/rules/variants.smk", line 12, in __rule_download_snpeff
File "/usr/local/envs/spritz/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job download_snpeff since they might be corrupted:
SnpEff_4.3_SmithChemWisc_v2.zip
Trying to restart job 8.
[Thu Aug 13 10:49:45 2020]
rule download_snpeff:
output: SnpEff/snpEff.config, SnpEff/snpEff.jar, SnpEff_4.3_SmithChemWisc_v2.zip
log: data/SnpEffInstall.log
jobid: 8
Analysis complete for test.trim_1.fastq.gz
Analysis complete for test.trim_2.fastq.gz
Analysis complete for test_2.fastq
Analysis complete for test_1.fastq
[Thu Aug 13 10:51:32 2020]
Finished job 24.
3 of 17 steps (18%) done
[Thu Aug 13 10:51:32 2020]
rule hisat2_align_bam:
input: data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic.1.ht2, analysis/trimmed/test.trim_1_fastqc.html, analysis/trimmed/test.trim_1.fastq.gz, analysis/trimmed/test.trim_2.fastq.gz, data/ensembl/Homo_sapiens.GRCh38.82.splicesites.txt
output: analysis/test.sorted.bam
log: analysis/test.hisat2.log
jobid: 21
wildcards: dir=analysis, fq=test
threads: 12
[Thu Aug 13 10:51:41 2020]
Error in rule download_snpeff:
jobid: 8
output: SnpEff/snpEff.config, SnpEff/snpEff.jar, SnpEff_4.3_SmithChemWisc_v2.zip
log: data/SnpEffInstall.log
RuleException:
CalledProcessError in line 12 of /app/rules/variants.smk:
Command ' set -euo pipefail; (wget https://github.com/smith-chem-wisc/SnpEff/releases/download/4.3_SCW1/SnpEff_4.3_SmithChemWisc_v2.zip && unzip SnpEff_4.3_SmithChemWisc_v2.zip -d SnpEff) &> data/SnpEffInstall.log ' returned non-zero exit status 127.
File "/app/rules/variants.smk", line 12, in __rule_download_snpeff
File "/usr/local/envs/spritz/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job download_snpeff since they might be corrupted:
SnpEff_4.3_SmithChemWisc_v2.zip
Trying to restart job 8.
[Thu Aug 13 10:51:41 2020]
rule download_snpeff:
output: SnpEff/snpEff.config, SnpEff/snpEff.jar, SnpEff_4.3_SmithChemWisc_v2.zip
log: data/SnpEffInstall.log
jobid: 8
[Thu Aug 13 10:53:21 2020]
Error in rule download_snpeff:
jobid: 8
output: SnpEff/snpEff.config, SnpEff/snpEff.jar, SnpEff_4.3_SmithChemWisc_v2.zip
log: data/SnpEffInstall.log
RuleException:
CalledProcessError in line 12 of /app/rules/variants.smk:
Command ' set -euo pipefail; (wget https://github.com/smith-chem-wisc/SnpEff/releases/download/4.3_SCW1/SnpEff_4.3_SmithChemWisc_v2.zip && unzip SnpEff_4.3_SmithChemWisc_v2.zip -d SnpEff) &> data/SnpEffInstall.log ' returned non-zero exit status 127.
File "/app/rules/variants.smk", line 12, in __rule_download_snpeff
File "/usr/local/envs/spritz/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job download_snpeff since they might be corrupted:
SnpEff_4.3_SmithChemWisc_v2.zip
[Thu Aug 13 11:08:44 2020]
Finished job 21.
4 of 17 steps (24%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /app/.snakemake/log/2020-08-13T104752.609569.snakemake.log

Best,

Finn

**Comment by acesnik** [comment]
Hi Finn,

I forgot to add `unzip` into the environment, and my testing didn't catch that. I updated the environment here: https://github.com/smith-chem-wisc/Spritz/pull/184, and the docker image is built again, so feel free to try it again.

I was able to replicate the error:

```
2020-08-13 18:16:18 (1.18 MB/s) - 'SnpEff_4.3_SmithChemWisc_v2.zip' saved [179641071/179641071]
/bin/bash: unzip: command not found
```

And now, it completes that step:

```
2020-08-13 18:37:28 (1.11 MB/s) - 'SnpEff_4.3_SmithChemWisc_v2.zip' saved [179641071/179641071]

Archive:  SnpEff_4.3_SmithChemWisc_v2.zip
  inflating: SnpEff/.classpath       
 extracting: SnpEff/.gitattributes   
  inflating: SnpEff/.gitignore       
 . . .
```

**Comment by finnbenned** [comment]
Dear Anthony,

Now the software finishes like a charm – thanks much for your help.

Best,

Finn

**Comment by acesnik** [comment]
That's great to hear! Glad to help.
